[package]
authors = ["Heliax AG <hello@heliax.dev>"]
edition = "2018"
license = "GPL-3.0"
name = "filter"
resolver = "2"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
anoma_vm_env = {path = "../../vm_env"}
borsh = "0.9.0"
wee_alloc = "0.4.5"

[profile.release]
# smaller and faster wasm https://rustwasm.github.io/book/reference/code-size.html#compiling-with-link-time-optimizations-lto
lto = true
# simply terminate on panics, no unwinding
panic = "abort"
