[package]
authors = ["Heliax AG <hello@heliax.dev>"]
edition = "2018"
license = "GPL-3.0"
name = "anoma_shared"
resolver = "2"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
js_bindgen = ["wasm-bindgen"]
# for integration tests and test utilies
testing = [
  "proptest",
  "rand",
  "rand_core",
]
wasm-runtime = [
  "loupe",
  "parity-wasm",
  "pwasm-utils",
  "wasmer-compiler-singlepass",
  "wasmer-compiler-cranelift",
  "wasmer-engine-universal",
  "wasmer-vm",
  "wasmer",
]
ibc-vp = [
  "ibc",
  "ibc-proto",
  "tendermint-proto",
]

[dependencies]
bech32 = "0.8.0"
borsh = "0.9.0"
chrono = "0.4.19"
ed25519-dalek = {version = "1.0.1", default-features = false, features = ["rand", "u64_backend", "serde"]}
hex = "0.4.2"
ibc = {git = "https://github.com/informalsystems/ibc-rs", rev = "3f0d4bc38a3d737cbd289c2087d09228bdb7b07f", features = ["mocks"], optional = true}
ibc-proto = {git = "https://github.com/informalsystems/ibc-rs", rev = "3f0d4bc38a3d737cbd289c2087d09228bdb7b07f", optional = true}
itertools = "0.10.0"
loupe = {version = "0.1.3", optional = true}
parity-wasm = {version = "0.42.2", optional = true}
proptest = {version = "1.0.0", optional = true}
prost = "0.7.0"
prost-types = "0.7.0"
pwasm-utils = {version = "0.18.0", optional = true}
wasm-bindgen = {version = "0.2.73", features = ["serde-serialize"], optional = true}
# TODO the older versions of rand and rand_core are currently required to avoid mismatching version issue (https://github.com/dalek-cryptography/ed25519-dalek/pull/159)
rand = {version = "0.7", optional = true}
rand_core = {version = "0.5", optional = true}
rust_decimal = "1.14.3"
serde = {version = "1.0.125", features = ["derive"]}
sha2 = "0.9.3"
# We switch off "blake2b" because it cannot be compiled to wasm
sparse-merkle-tree = {git = "https://github.com/heliaxdev/sparse-merkle-tree", branch = "tomas/encoding-0.9.0b", default-features = false, features = ["std", "borsh"]}
tendermint-proto = {version = "0.20.0", optional = true}
thiserror = "1.0.26"
tracing = "0.1.26"
wasmer = {version = "2.0.0", optional = true}
wasmer-compiler-cranelift = {version = "2.0.0", optional = true}
wasmer-compiler-singlepass = {version = "2.0.0", optional = true}
wasmer-engine-universal = {version = "2.0.0", optional = true}
wasmer-vm = {version = "2.0.0", optional = true}
wasmparser = "0.79.0"

[dev-dependencies]
assert_matches = "1.5.0"
pretty_assertions = "0.7.2"
proptest = "1.0.0"
test-env-log = {version = "0.2.7", default-features = false, features = ["trace"]}
tracing-subscriber = {version = "0.2.18", default-features = false, features = ["env-filter", "fmt"]}
wasm-bindgen-test = "0.3.24"

[build-dependencies]
tonic-build = "0.4.0"
